# --- General Configuration ---
# ALGORITHM: The main heuristic to run. Currently only SA is supported.
# Options: SA
ALGORITHM = SA

# TRIAL_RUNS: How many independent runs to perform.
TRIAL_RUNS = 21

# TERMINATION_EVALS_FACTOR: The base number of evaluations for the termination condition.
# The final termination value is: TERMINATION_EVALS_FACTOR * PROBLEM_SIZE
TERMINATION_EVALS_FACTOR = 25000


# --- Simulated Annealing (SA) Specific Configuration ---

# SA_OPERATOR: The neighborhood operator to use within the SA algorithm.
# Options: TWO_OPT, SWAP, RUIN_RECREATE
SA_OPERATOR = SWAP

# SA_INITIAL_TEMPERATURE: The starting temperature for the SA process.
SA_INITIAL_TEMPERATURE = 2.5

# SA_COOLING_RATE: The multiplicative factor for cooling the temperature.
SA_COOLING_RATE = 0.99

# SA_REHEAT_THRESHOLD: Number of iterations without improvement before reheating.
SA_REHEAT_THRESHOLD = 5000

# SA_ITERATIONS_PER_CALL: Number of neighbors to generate in each main loop.
SA_ITERATIONS_PER_CALL = 100
# --- Penalty Function Weights ---
# Set high enough to force the final solution to be feasible.
PENALTY_WEIGHT_ENERGY = 100.0
PENALTY_WEIGHT_CAPACITY = 100.0